name = "miniflare-typescript-esbuild-jest"
main = "dist/index.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "KVID" }
]

[build]
command = "node build.js"

