name = "miniflare-typescript-esbuild-jest-sched"
main = "dist/index_sched.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "e759e181747c45fc9aa1acf12afdb7b4" }
  

[triggers]
crons = ["*/1 * * * *"]

[build]
command = "node build_sched.js"

