name = "miniflare-typescript-esbuild-jest"
main = "dist/src/index.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "e759e181747c45fc9aa1acf12afdb7b4" }
]

[build]
command = "node build.js"

