name = "miniflare-typescript-esbuild-jest-sched"
main = "dist/index_sched.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "e29b263ab50e42ce9b637fa8370175e8" }
  

[triggers]
crons = ["*/1 * * * *"]

[build]
command = "node build_sched.js"

