name = "miniflare-typescript-esbuild-jest-sched"
main = "dist/index_sched.mjs"
compatibility_date = "2022-05-28"
compatibility_flags = []

kv_namespaces = [
  { binding = "KV_NAMESPACE", id = "KV_ID" }

[triggers]
crons = ["*/1 * * * *"]

[build]
command = "node build_sched.js"

